spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ── Email (Gmail SMTP) ──────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=istociustin9@gmail.com
spring.mail.password=iyvmdqphyfyhjket
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# emailul care primeste alertele de securitate
app.admin-email=istociustin9@gmail.com

# ── HTTPS ──────────────────────────────────────────
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit